env:
    # fushar's auth token
    - secure: "Y+fpnS4JF4CzjT/+oFb0GaIyDDQj/Gbpc1ljpPnnNw9h0zjhdgciKKhagzW4FIqoA+rhIyGvtKmgsgTJi7qAhRBft23MJ6u6WcRORWwz6p4LgRpL//fhRLjOFG3IfFLD8vSOwrDINBPJLNgbNPfX1soZqCBzT/UEe2yPhbul1xc="

before_install:
    - sudo apt-get update
    - wget launchpadlibrarian.net/128239195/latexmk_4.35-0ubuntu1_all.deb

install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-lang-other
    - sudo dpkg -i latexmk_4.35-0ubuntu1_all.deb
    - sudo ./setup.sh

script:
    - make

after_success:
    - ./publish_pdf.sh
